# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='index',
            field=models.IntegerField(blank=True, default=0, verbose_name='Почтовый индекс'),
        ),
    ]
