# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_auto_20170227_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='office',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер дома/офиса'),
        ),
    ]
