# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0006_auto_20170529_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='users/', verbose_name='Аватар'),
        ),
    ]
