# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.SmallIntegerField(choices=[('1', 'Заявка подана'), ('2', 'Рассмотрена'), ('3', 'Подтверждена'), ('4', 'Отклонена')], null=True, verbose_name='Статус'),
        ),
    ]
